set_property IOSTANDARD LVCMOS25 [get_ports clk]
set_property PACKAGE_PIN Y9 [get_ports clk]

set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS25} [get_ports {reset}]
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS25} [get_ports {q[0]}]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS25} [get_ports {q[1]}]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS25} [get_ports {q[2]}]
set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS25} [get_ports {q[3]}]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS25} [get_ports {q[4]}]
set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS25} [get_ports {q[5]}]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS25} [get_ports {q[6]}]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS25} [get_ports {q[7]}]

set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS25} [get_ports {btn1}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS25} [get_ports {btn2}]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS25} [get_ports {btn3}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS25} [get_ports {btn4}]

set_property -dict {PACKAGE_PIN AB10  IOSTANDARD LVCMOS25} [get_ports {x1[0]}]
set_property -dict {PACKAGE_PIN AB9   IOSTANDARD LVCMOS25} [get_ports {x1[1]}]
set_property -dict {PACKAGE_PIN AA6   IOSTANDARD LVCMOS25} [get_ports {x1[2]}]
set_property -dict {PACKAGE_PIN Y11   IOSTANDARD LVCMOS25} [get_ports {x1[3]}]
set_property -dict {PACKAGE_PIN Y10   IOSTANDARD LVCMOS25} [get_ports {x1[4]}]
set_property -dict {PACKAGE_PIN AB6   IOSTANDARD LVCMOS25} [get_ports {x1[5]}]
set_property -dict {PACKAGE_PIN Y4    IOSTANDARD LVCMOS25} [get_ports {x1[6]}]

set_property -dict {PACKAGE_PIN AA11  IOSTANDARD LVCMOS25} [get_ports {x2[0]}]
set_property -dict {PACKAGE_PIN AB11  IOSTANDARD LVCMOS25} [get_ports {x2[1]}]
set_property -dict {PACKAGE_PIN AA7   IOSTANDARD LVCMOS25} [get_ports {x2[2]}]
set_property -dict {PACKAGE_PIN AB2   IOSTANDARD LVCMOS25} [get_ports {x2[3]}]
set_property -dict {PACKAGE_PIN AB1   IOSTANDARD LVCMOS25} [get_ports {x2[4]}]
set_property -dict {PACKAGE_PIN AB5   IOSTANDARD LVCMOS25} [get_ports {x2[5]}]
set_property -dict {PACKAGE_PIN AB7   IOSTANDARD LVCMOS25} [get_ports {x2[6]}]

